:: This is comment

@echo off

set "BinPath=F:\Games\Steam\steamapps\common\GarrysMod\bin"

set  Dir[0]=GearAssembly
set  IDs[0]=384782853

title Addon updater/publisher

echo Press Crtl+C to terminate !
echo Press a key if you dont want to wait ! 
echo Rinning in %CD%.
echo Npp Find --\h{1,}\n-- replace --\n-- in unix format before commit !
echo.  

timeout 10

set "x=0"

:SymLoop
if defined Dir[%x%]  (
  if defined IDs[%x%]  (
    call %BinPath%/gmad.exe create -folder "%CD%/%%Dir[%x%]%%" -out "%CD%/%%Dir[%x%]%%.gma"
    call %BinPath%/gmpublish.exe update -addon "%CD%/%%Dir[%x%]%%.gma" -id "%%IDs[%x%]%%" -changes "Generated by Batch!"
    echo.
    call echo !!! %%Dir[%x%]%% Published !!!
    echo.
    set /a "x+=1"
    GOTO :SymLoop
  )
)

echo.
echo.
timeout 500
exit